### ISSUE TITLE
Doesn't work try catch syntax in javascript

### ISSUE THREAD

**Issue by medliii** [randunel/imacros#1]
Hi!
I write some script using js in firefox.
But i can't use try catch syntax.

``` javascript
function NotImplementedError(message) {
    this.name = "NotImplementedError";
    this.message = (message || "");
}
NotImplementedError.prototype = Error.prototype;

try {
    var e = new NotImplementedError("NotImplementedError message");
    throw e;
} catch (ex1) {
    alert(ex1.stack);
    alert("ex1 instanceof NotImplementedError = " + (ex1 instanceof NotImplementedError));
    alert("ex1 instanceof Error = " + (ex1 instanceof Error));
    alert("ex1.name = " + ex1.name);
    alert("ex1.message = " + ex1.message);
}
```

Error:

> TypeError: ex1 is undefined

But it valid js code.
Could you help me?

**Comment by randunel** [comment]
Hello @medliii.

You are using [inheritance](https://developer.mozilla.org/en/docs/Web/JavaScript/Inheritance_and_the_prototype_chain) the wrong way. Specifically, your code doesn't work because of `Something.prototype = SomethingElse.prototype`.

You should direct questions such as this one to [stackoverflow](https://www.stackoverflow.com).

**Comment by medliii** [comment]
It doesn't work even without inheritance:

``` javascript
try {
    throw new Error("NotImplementedError message");
} catch (ex1) {
    alert("ex1 instanceof Error = " + (ex1 instanceof Error));
    alert("ex1.name = " + ex1.name);
    alert("ex1.message = " + ex1.message);
}
```

> TypeError: ex1 is undefined, line 5
